version: '3.8'
services:
  frontend:
    container_name: frontend-banking
    build:
      context: .
      args:
        ENV: dev  
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - ENV=dev  
    networks:
      - frontend-banking

networks:
  frontend-banking:
    driver: bridge
